# -*- coding: utf-8 -*-
"""analytical_queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEotxNAXmeX-T8MrJ30gMubJLUDfeO_o
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from collections import Counter

"""# Load (Warehouse)"""

def run_query(query, title):
    print(f"\n[Query] {title}")
    result = pd.read_sql(query, conn)
    display(result)

print("\n--- 8 Query Analitik ---")
q1 = "SELECT order_month, SUM(total_order_value) as revenue FROM fact_orders GROUP BY order_month ORDER BY order_month"
run_query(q1, "1. Tren Penjualan Bulanan")

q2 = "SELECT product_category_name, COUNT(order_id) as qty FROM fact_orders WHERE product_category_name != 'unknown' GROUP BY product_category_name ORDER BY qty DESC LIMIT 10"
run_query(q2, "2. Top 10 Kategori Produk")

q3 = "SELECT order_hour, COUNT(order_id) as trx FROM fact_orders GROUP BY order_hour ORDER BY trx DESC"
run_query(q3, "3. Jam Belanja Teramai")

q4 = "SELECT customer_state, AVG(total_freight_value) as avg_ongkir FROM fact_orders GROUP BY customer_state ORDER BY avg_ongkir DESC"
run_query(q4, "4. Rata-rata Ongkir per Wilayah")

q5 = "SELECT order_id, total_order_value FROM fact_orders WHERE total_order_value > (SELECT AVG(total_order_value)*3 FROM fact_orders) LIMIT 10"
run_query(q5, "5. Deteksi Anomali (High Value)")

q6 = "SELECT CASE WHEN day_name IN ('Saturday','Sunday') THEN 'Weekend' ELSE 'Weekday' END as day_type, COUNT(order_id) as trx, AVG(total_order_value) as avg_spend FROM fact_orders GROUP BY day_type"
run_query(q6, "6. Performa Weekday vs Weekend")

q7 = "SELECT customer_id, SUM(total_order_value) as total_spent FROM fact_orders GROUP BY customer_id ORDER BY total_spent DESC LIMIT 10"
run_query(q7, "7. Top 10 Sultan")

q8 = "SELECT product_category_name, AVG(total_order_value) as avg_price FROM fact_orders WHERE product_category_name != 'unknown' GROUP BY product_category_name"
run_query(q8, "8. Rata-rata Harga per Kategori")

