# -*- coding: utf-8 -*-
"""insert_fact_dim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEotxNAXmeX-T8MrJ30gMubJLUDfeO_o
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from collections import Counter

"""# Load (Warehouse)"""

conn = sqlite3.connect("olist_dw.db")

fact_orders.to_sql("fact_orders", conn, if_exists="replace", index=False)
customers.to_sql("dim_customers", conn, if_exists="replace", index=False)
products.to_sql("dim_products", conn, if_exists="replace", index=False)
payments.to_sql("dim_payments", conn, if_exists="replace", index=False)
items.to_sql("dim_items", conn, if_exists="replace", index=False)
reviews.to_sql("dim_reviews", conn, if_exists="replace", index=False)
orders.to_sql("dim_orders", conn, if_exists="replace", index=False)

