# -*- coding: utf-8 -*-
"""extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1jFsyIX_ct5A-NaICXYgAZLLLzNENb4
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

conn = sqlite3.connect("olist_warehouse.db")

items = pd.read_csv('https://drive.google.com/uc?id=1YAIZ1v2GZPE5epki5dsCdVp5zQLSZaEl')
payments = pd.read_csv('https://drive.google.com/uc?id=1OhNps6JLk5ttkVeNN5PvApDF4_m7l_JN')
reviews = pd.read_csv('https://drive.google.com/uc?id=1Y72vau9ATI62bI9V9MiSVF9C-nV49aVE')
customers = pd.read_csv('https://drive.google.com/uc?id=1eKoY4f2iRseaouKZgAl3JEdVZslZKrZ5')
orders = pd.read_csv('https://drive.google.com/uc?id=1QArWoteWXvlftx5Ra4ZXyg8YM18WDBTs')
products = pd.read_csv('https://drive.google.com/uc?id=1UcWev0Fb3CxGdGmeLxAJ2TLiL5JsFuym')
category = pd.read_csv('https://drive.google.com/uc?id=1jTV_ASCVRQXN2jFLomXp36toKW3cORgN')

items.to_sql("raw_order_items", conn, if_exists="replace", index=False)
payments.to_sql("raw_order_payments", conn, if_exists="replace", index=False)
reviews.to_sql("raw_order_reviews", conn, if_exists="replace", index=False)
customers.to_sql("raw_customers", conn, if_exists="replace", index=False)
orders.to_sql("raw_orders", conn, if_exists="replace", index=False)
products.to_sql("raw_products", conn, if_exists="replace", index=False)
category.to_sql("raw_product_category_translation", conn, if_exists="replace", index=False)

conn.execute("ALTER TABLE raw_order_items ADD COLUMN load_timestamp DATETIME;")
conn.execute("ALTER TABLE raw_order_payments ADD COLUMN load_timestamp DATETIME;")
conn.execute("ALTER TABLE raw_order_reviews ADD COLUMN load_timestamp DATETIME;")
conn.execute("ALTER TABLE raw_customers ADD COLUMN load_timestamp DATETIME;")
conn.execute("ALTER TABLE raw_orders ADD COLUMN load_timestamp DATETIME;")
conn.execute("ALTER TABLE raw_products ADD COLUMN load_timestamp DATETIME;")
conn.execute("ALTER TABLE raw_product_category_translation ADD COLUMN load_timestamp DATETIME;")
conn.commit()

conn.execute("UPDATE raw_order_items SET load_timestamp = CURRENT_TIMESTAMP;")
conn.execute("UPDATE raw_order_payments SET load_timestamp = CURRENT_TIMESTAMP;")
conn.execute("UPDATE raw_order_reviews SET load_timestamp = CURRENT_TIMESTAMP;")
conn.execute("UPDATE raw_customers SET load_timestamp = CURRENT_TIMESTAMP;")
conn.execute("UPDATE raw_orders SET load_timestamp = CURRENT_TIMESTAMP;")
conn.execute("UPDATE raw_products SET load_timestamp = CURRENT_TIMESTAMP;")
conn.execute("UPDATE raw_product_category_translation SET load_timestamp = CURRENT_TIMESTAMP;")
conn.commit()