# -*- coding: utf-8 -*-
"""Load_warehouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSN9HdhiV5B98sRvVi7azl4c_szUNkuV
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

conn = sqlite3.connect("olist_warehouse.db")

conn.execute("""
DROP TABLE IF EXISTS fact_orders;""")
conn.execute("""
CREATE TABLE fact_orders AS
SELECT
    f.order_id,
    f.product_id,
    ord.customer_id,
    ord.order_purchase_timestamp,
    f.price,
    f.freight_value,
    ov.total_order_value,
    f.shipping_ratio,
    f.price_norm,
    f.freight_norm,
    p.total_payment_value,
    r.review_score,
    r.review_category,
    r.order_month,
    c.customer_city,
    c.customer_state,
    dp.product_category_name

FROM feat_item_features f
LEFT JOIN feat_order_value ov
    ON f.order_id = ov.order_id
LEFT JOIN clean_orders ord
    ON f.order_id = ord.order_id
LEFT JOIN clean_payments p
    ON f.order_id = p.order_id
LEFT JOIN clean_reviews r
    ON f.order_id = r.order_id
LEFT JOIN clean_customers c
    ON ord.customer_id = c.customer_id
LEFT JOIN dim_product dp
    ON f.product_id = dp.product_id;

""")

conn.commit()