# -*- coding: utf-8 -*-
"""Transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7Cl1KcVQ09qfpkQWSeTmUcsbsoq8tIJ
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

conn = sqlite3.connect("olist_warehouse.db")

conn.execute("""
CREATE TABLE clean_payments AS
SELECT
    order_id,
    SUM(payment_value) AS total_payment_value
FROM raw_order_payments
WHERE payment_value IS NOT NULL
GROUP BY order_id;
""")

conn.execute("""
CREATE TABLE clean_reviews AS
SELECT
    order_id,
    review_score,
    CASE
        WHEN review_score >= 4 THEN 'good'
        ELSE 'bad'
    END AS review_category,
    CAST(strftime('%m', review_creation_date) AS INTEGER) AS order_month
FROM raw_order_reviews
WHERE review_score IS NOT NULL;
""")

conn.execute("""
CREATE TABLE clean_customers AS
SELECT
    customer_id,
    customer_unique_id,
    customer_city,
    customer_state
FROM raw_customers;
""")

conn.execute("""
CREATE TABLE order_value AS
SELECT
    order_id,
    SUM(price) AS total_order_value
FROM raw_order_items
GROUP BY order_id;
""")

conn.execute("""
DROP TABLE IF EXISTS clean_orders;
""")

conn.execute("""
CREATE TABLE clean_orders AS
SELECT
    order_id,
    customer_id,
    order_purchase_timestamp
FROM raw_orders;
""")

conn.commit()

conn.execute("""
DROP TABLE IF EXISTS feat_order_value;
""")

conn.execute("""
CREATE TABLE feat_order_value AS
SELECT
    order_id,
    SUM(price) AS total_order_value
FROM raw_order_items
GROUP BY order_id;
""")

conn.commit()

conn.execute("""
DROP TABLE IF EXISTS feat_item_features;
""")

conn.execute("""
CREATE TABLE feat_item_features AS
SELECT
    order_id,
    product_id,
    price,
    freight_value,

    -- Feature 1
    CASE
        WHEN price > 0 THEN freight_value / price
        ELSE 0
    END AS shipping_ratio,

    -- Feature 2
    price / (SELECT MAX(price) FROM raw_order_items) AS price_norm,

    -- Feature 3
    freight_value / (SELECT MAX(freight_value) FROM raw_order_items) AS freight_norm

FROM raw_order_items;
""")

conn.commit()

conn.execute("""
CREATE TABLE dim_product AS
SELECT
    p.product_id,
    COALESCE(t.product_category_name_english, p.product_category_name)
        AS product_category_name
FROM raw_products p
LEFT JOIN raw_product_category_translation t
    ON p.product_category_name = t.product_category_name;
""")

conn.commit()