# -*- coding: utf-8 -*-
"""extract_source2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fP-BUttp7YzTCwIts0hKLhCMJKX0Az3g
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from collections import Counter

"""# Extract"""

def extract_etl_source2():
  start = time.time()
  items = pd.read_csv('https://drive.google.com/uc?id=16yLKQ6l_o7L3irnaVHOPoHdv57pgpV3g')
  payments = pd.read_csv('https://drive.google.com/uc?id=1OhNps6JLk5ttkVeNN5PvApDF4_m7l_JN')
  reviews = pd.read_csv('https://drive.google.com/uc?id=1Y72vau9ATI62bI9V9MiSVF9C-nV49aVE')
  print("Payments:", payments.shape)
  print("Items:", items.shape)
  print("Reviews:", reviews.shape)
  print("Time:", time.time() - start)
  return payments, items, reviews

payments, items, reviews = extract_etl_source2()