# -*- coding: utf-8 -*-
"""extract_source3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgJgpgwNrl5S25ZrcUz7NXatiBctv6wC
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from collections import Counter

"""# Extract"""

def extract_etl_additional():
  start = time.time()
  orders = pd.read_csv('https://drive.google.com/uc?id=1dT4i47ENRKfInNHLRRNEsM-UKosgQaY8')
  products = pd.read_csv('https://drive.google.com/uc?id=1UcWev0Fb3CxGdGmeLxAJ2TLiL5JsFuym')
  print("Orders:", orders.shape)
  print("Products:", products.shape)
  print("Time:", time.time() - start)
  return orders, products

orders, products = extract_etl_additional()