# -*- coding: utf-8 -*-
"""extract_source1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJSoNKLVXD90cUOlIZhIqG-TsypmoD3W
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from collections import Counter

"""# Extract"""

def extract_etl_source1():
  customers = pd.read_csv('https://drive.google.com/uc?id=1eKoY4f2iRseaouKZgAl3JEdVZslZKrZ5')
  start = time.time()
  print("Customers shape:", customers.shape)
  print("Time:", time.time() - start)
  return customers

customers = extract_etl_source1()