# -*- coding: utf-8 -*-
"""transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aivATPWfv0md-XQSh1ihlP1nxm62hBWV
"""

import pandas as pd
import numpy as np
import sqlite3
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from collections import Counter

"""# Transform

## Cleaning dan Standardisasi
"""

def clean_and_std(df):
    if df is not None and not df.empty:
        df.columns = df.columns.str.lower().str.replace(' ', '_')
        df.drop_duplicates(inplace=True)
    return df

orders = clean_and_std(orders)
items = clean_and_std(items)
payments = clean_and_std(payments)
reviews = clean_and_std(reviews)
products = clean_and_std(products)
customers = clean_and_std(customers)

if 'product_category_name' in products.columns:
    products['product_category_name'].fillna('others', inplace=True)
    products['product_category_name'] = products['product_category_name'].str.replace('_', ' ')
    products['product_category_name'] = products['product_category_name'].str.title()

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

products.head()

"""## Missing Value"""

reviews['review_comment_title'].fillna('unknown', inplace=True)
reviews['review_comment_message'].fillna('unknown', inplace=True)

"""## Outlier"""

Q1 = items['price'].quantile(0.25)
Q3 = items['price'].quantile(0.75)
IQR = Q3 - Q1
items = items[~((items['price'] < (Q1 - 1.5 * IQR)) | (items['price'] > (Q3 + 1.5 * IQR)))]

"""## Standardisasi"""

scaler = MinMaxScaler()
items[["price","freight_value"]] = scaler.fit_transform(
    items[["price","freight_value"]]
)

le = LabelEncoder()
customers["customer_state_encoded"] = le.fit_transform(customers["customer_state"])

"""## Feature Engineering"""

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_month'] = orders['order_purchase_timestamp'].dt.month
orders['order_hour'] = orders['order_purchase_timestamp'].dt.hour
orders['day_name'] = orders['order_purchase_timestamp'].dt.day_name()

if 'product_category_name' in products.columns:
    items = items.merge(products[['product_id', 'product_category_name']], on='product_id', how='left')
    items['product_category_name'].fillna('others', inplace=True)

items_agg = items.groupby('order_id').agg({
    'price': 'sum',
    'freight_value': 'sum',
    'product_id': 'count',
    'product_category_name': 'first'
}).reset_index().rename(columns={
    'price': 'total_order_value',
    'freight_value': 'total_freight_value',
    'product_id': 'item_count'
})

payments_agg = payments.groupby('order_id').agg({'payment_value': 'sum', 'payment_sequential': 'count'}).reset_index()
payments_agg.rename(columns={'payment_value': 'total_payment_value', 'payment_sequential': 'payment_count'}, inplace=True)

reviews['review_category'] = reviews['review_score'].apply(lambda x: 'good' if x >= 4 else 'bad')
reviews_agg = reviews.groupby('order_id').agg({'review_score': 'mean', 'review_category': 'first'}).reset_index()

"""## Join Data"""

fact_orders = orders.merge(items_agg, on='order_id', how='left') \
    .merge(payments_agg, on='order_id', how='left') \
    .merge(reviews_agg, on='order_id', how='left') \
    .merge(customers[['customer_id', 'customer_state', 'customer_city']], on='customer_id', how='left')

fact_orders['total_order_value'].fillna(0, inplace=True)
fact_orders['total_freight_value'].fillna(0, inplace=True)
fact_orders['review_score'].fillna(-1, inplace=True)
fact_orders['product_category_name'].fillna('unknown', inplace=True)

print(f"Transform Selesai. Ukuran Fact Table: {fact_orders.shape}")

"""## Data Validation"""

print("\n--- [6.2.4] Validasi Kualitas Data ---")

# 1. Datatype Check (Kesesuaian Tipe Data)
assert fact_orders['total_order_value'].dtype == 'float64', "Error: Tipe data order_value salah!"
print("✓ 1. Datatype Check: PASS")

# 2. Uniqueness Check (Keunikan Data)
if fact_orders['order_id'].is_unique:
    print("✓ 2. Uniqueness Check: PASS")
else:
    print("X 2. Uniqueness Check: FAIL (Ada duplikasi Order ID)")

# 3. Range Check (Rentang Nilai)
valid_reviews = fact_orders[fact_orders['review_score'] > 0]
if valid_reviews['review_score'].between(1, 5).all():
    print("✓ 3. Range Check (Score 1-5): PASS")
else:
    print("X 3. Range Check: FAIL (Ada skor di luar 1-5)")

# 4. Referential Integrity (Keterhubungan Data)
if fact_orders['customer_state'].notnull().all():
    print("✓ 4. Referential Integrity: PASS")
else:
    print(f"! Warning: Ada {fact_orders['customer_state'].isnull().sum()} order kehilangan data customer.")

# 5. Null Check (Kelengkapan Data)
cols_critical = ['order_purchase_timestamp', 'total_order_value', 'total_freight_value']
if fact_orders[cols_critical].isnull().sum().sum() == 0:
    print("✓ 5. Null Check: PASS (Data Kritis Lengkap)")
else:
    print("X 5. Null Check: FAIL (Ada data kritis yang kosong/NaN)")

# 6. Distribusi (Kewajaran Statistik)
if (fact_orders['total_order_value'] >= 0).all():
    print("✓ 6. Distribusi (Logic): PASS (Tidak ada nilai transaksi negatif)")
else:
    print("X 6. Distribusi: FAIL (Ditemukan nilai transaksi negatif)")

print("\n[Info Distribusi Nilai Belanja]")
print(fact_orders['total_order_value'].describe().round(2))